matrix:
  fast_finish: true

environment:
  global:
    # Environment variables used by astropy helpers
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
  ANACONDA_TOKEN:
    secure: 8RgmvPc4Rfu1PELT7hOKi/a3d0zevmFKS8qL1ZdmCZb1Gx1X2pZPqOEoFqcWYDtm

  matrix:
    - PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      ARCH: "x86"
      platform: "x86"
    - PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      ARCH: "amd64"
      platform: "x64"

install:
  # Astropy ci-helpers. See https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Install dependencies
  - "%CMD_IN_ENV% conda install conda-build anaconda-client -q -y"
  - "%CMD_IN_ENV% conda-build recipe"

build: false

on_success:
  # upload to anaconda cloud
  - cmd: anaconda -t %ANACONDA_TOKEN% upload --force C:\conda\conda-bld\win-$PYTHON_ARCH$\swashes-*.tar.bz2

