version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            conda install conda-build anaconda-client cmake -y
            conda install -c anaconda make gcc -v -y
      - run: conda-build recipe
      # upload
      - run:
          name: Anaconda upload
          command: python ci-tools/anaconda-upload.py
